### ISSUE TITLE
[jython-kernel] Protocol problems

### ISSUE THREAD

**Issue by david11rsww** [fiber-space/jupyter-kernel-jsr223#12]
As JDK8 not suppotted, I installed java 1.7.0_79. And still the mission control is reported 5.3. 
This is the ERROR:

Exception in thread "Thread-0" java.lang.RuntimeException: [jupyter-kernel] Protocol version 5.3not supported by this kernel

**Comment by bdw429s** [comment]
Hi @david11rsww were you able to get around the issues with protocol version 5.3?  cc/ @fiber-space

**Comment by david11rsww** [comment]
I have installed a different kernel that support Java8, and it runs with no problem.
